/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiproject11;

/**
 
    public checkCredits() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
*/

import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import java.awt.Font;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;


public class checkCredits {

	protected JFrame frame;
	private JTable table;
	private JScrollPane scrollPane;
	private JLabel lblStudentLogin;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					checkCredits window = new checkCredits();
					window.frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the application.
	 */
	public checkCredits() {
		initialize();
	}
        
        
        String ID ;
	/**
	 * Initialize the contents of the frame.
	 */
	public void initialize() {
		frame = new JFrame();
		frame.setBounds(100, 100, 988, 497);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.getContentPane().setLayout(null);
		
		scrollPane = new JScrollPane();
		scrollPane.setBounds(0, 86, 974, 374);
		frame.getContentPane().add(scrollPane);
		
		table = new JTable();
		scrollPane.setViewportView(table);
		
		DefaultTableModel model = (DefaultTableModel) table.getModel();
		model.addColumn("ID");
		model.addColumn("Total Credits");
                model.addColumn("Sem");
		model.addColumn("Type Of Degree");
                StudentOptions op = new StudentOptions();
                ID = op.id;
		try {
			Class.forName("com.mysql.cj.jdbc.Driver");
			Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/credit_bank?autoReconnect=true&useSSL=false", "root", "root");
			System.out.println(ID);
			PreparedStatement ps =  conn.prepareStatement("Select * from studentcredit where Id="+ID);
                        PreparedStatement pst =  conn.prepareStatement("Select * from studentinformation where Id="+ID);
                        ResultSet rs = ps.executeQuery();
                        ResultSet rs1 = pst.executeQuery();
                        while(rs.next()&&rs1.next())
                        {
                                model.addRow(new Object[] {rs.getString("Id"), rs.getString("TotalCredit"), rs1.getString("CurrentSem"), rs.getString("TypeOfDegree")});
                        }			
                    }
		catch(Exception e2)
		{
			System.out.println(e2);
		}
		
		lblStudentLogin = new JLabel("Check Credits");
		lblStudentLogin.setFont(new Font("Tahoma", Font.BOLD, 22));
		lblStudentLogin.setBounds(403, 25, 181, 50);
		frame.getContentPane().add(lblStudentLogin);
		
		
	}
	

	
	
}
